# Generated by Django 4.1.7 on 2023-03-16 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('last_week', models.TextField(blank=True, null=True, verbose_name='отчет за прошлую неделю')),
                ('current_week', models.TextField(blank=True, null=True, verbose_name='отчет за эту неделю')),
                ('next_week', models.TextField(blank=True, null=True, verbose_name='отчет на следующую неделю')),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False, verbose_name='Отчет отправлен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_report', to='users.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
