# Generated by Django 4.1.7 on 2023-03-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
