# Generated by Django 4.1.7 on 2023-03-16 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='dep_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
